spring.application.name=proman

spring.datasource.url=jdbc:postgresql://10.15.33.127:5432/proman?TimeZone=Asia/Calcutta
spring.datasource.username=proman_user
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Qm9nZXJTaWduYXR1cmVJc1NhZmVGb3JEZXZlbG9wbWVudCEyMzQ1Njc4OTA=

cloudinary.cloud-name=dou2gktzi
cloudinary.api-key=227132318869393
cloudinary.api-secret=vydyvOZak2mZho35QKLVPVRAkpU

app.upload.max-file-size=10MB
app.upload.max-request-size=11MB

spring.servlet.multipart.max-file-size=${app.upload.max-file-size}
spring.servlet.multipart.max-request-size=${app.upload.max-request-size}
